jpa.hibernate.show_sql=false
jpa.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
jpa.hibernate.hbm2ddl.auto=update

internet.availability.form.sugar.endpoint=http://10.245.34.151/custom/service/v4_custom/soap.php